feat: implements ttl and persist
nutsdb/nutsdb pull request #546
Opened 2023-12-14 02:12 UTC by ksankeerth

* implement ttl and persist
* docs for ttl, persist, put if exists, and put if not exists

Implements APIs for #517

2023-12-14 07:02 UTC, bigboss2063 requested changes

2023-12-14 15:00 UTC, ksankeerth commented
I've made the changes. When you have time, Please check. thanks!

2023-12-14 15:04 UTC, bigboss2063 commented
Hi, just a problem, if the remain TTL is less than 1s, what will be returned? @ksankeerth

2023-12-14 15:06 UTC, bigboss2063 commented
> Hi, just a problem, if the remain TTL is less than 1s, what will be returned? @ksankeerth

Like remaining 500ms

2023-12-14 15:11 UTC, ksankeerth commented
> > Hi, just a problem, if the remain TTL is less than 1s, what will be returned? @ksankeerth
> 
> Like remaining 500ms

Yeah, Your point is valid. It'll return 0 when casting 500ms to `int`. If You prefer, we may return milliseconds instead of seconds. 

I decided to return in seconds after looking at `TTL` of redis. https://redis.io/commands/ttl/

2023-12-14 15:15 UTC, bigboss2063 commented
> > > Hi, just a problem, if the remain TTL is less than 1s, what will be returned? @ksankeerth
> > 
> > 
> > Like remaining 500ms
> 
> Yeah, Your point is valid. It'll return 0 when casting 500ms to `int`. If You prefer, we may return milliseconds instead of seconds.
> 
> I decided to return in seconds after looking at `TTL` of redis. https://redis.io/commands/ttl/

I think so. Because our accuracy is only up to seconds, so I think it's okay to return 0 less than 1 second.

2023-12-14 15:21 UTC, ksankeerth commented
> > > > Hi, just a problem, if the remain TTL is less than 1s, what will be returned? @ksankeerth
> > > 
> > > 
> > > Like remaining 500ms
> > 
> > 
> > Yeah, Your point is valid. It'll return 0 when casting 500ms to `int`. If You prefer, we may return milliseconds instead of seconds.
> > I decided to return in seconds after looking at `TTL` of redis. https://redis.io/commands/ttl/
> 
> I think so. Because our accuracy is only up to seconds, so I think it's okay to return 0 less than 1 second.

I checked, We'll return 0 for 500ms https://go.dev/play/p/APO-EM5CeUy

2023-12-14 15:30 UTC, bigboss2063 commented on tx_btree.go
> +func (tx *Tx) updateIfExists(bucket string, key, value []byte, ttl uint32, updateTTLOnly bool) error {
We already have helper method named `update` and so on, maybe we can edit and reuse them?

2023-12-14 15:31 UTC, bigboss2063 commented
> > > > > Hi, just a problem, if the remain TTL is less than 1s, what will be returned? @ksankeerth
> > > > 
> > > > 
> > > > Like remaining 500ms
> > > 
> > > 
> > > Yeah, Your point is valid. It'll return 0 when casting 500ms to `int`. If You prefer, we may return milliseconds instead of seconds.
> > > I decided to return in seconds after looking at `TTL` of redis. https://redis.io/commands/ttl/
> > 
> > 
> > I think so. Because our accuracy is only up to seconds, so I think it's okay to return 0 less than 1 second.
> 
> I checked, We'll return 0 for 500ms https://go.dev/play/p/APO-EM5CeUy

OK, and we should add comment for this.

2023-12-15 02:19 UTC, ksankeerth commented
I've updated the PR with your suggestions.

2023-12-15 06:20 UTC, bigboss2063 approved these changes
LGTM!

2023-12-15 06:20 UTC, merged